# Generated by Django 4.1.3 on 2022-11-10 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=65)),
                ('cifnif_cliente', models.CharField(max_length=15)),
                ('dir_cliente', models.CharField(max_length=65)),
                ('pob_cliente', models.CharField(max_length=30)),
                ('cpo_cliente', models.CharField(max_length=10)),
                ('pro_cliente', models.CharField(max_length=30)),
                ('pai_cliente', models.CharField(max_length=30)),
                ('tipo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.tipo_cliente')),
            ],
        ),
    ]
