# Generated by Django 4.1.3 on 2022-11-10 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo_cliente',
            options={'ordering': ['id'], 'verbose_name': 'Tipo de cliente', 'verbose_name_plural': 'Tipo de Clientes'},
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cifnif_cliente',
            field=models.CharField(max_length=15, verbose_name='NIF/CIF'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cpo_cliente',
            field=models.CharField(max_length=10, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='dir_cliente',
            field=models.CharField(max_length=65, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre_cliente',
            field=models.CharField(max_length=65, verbose_name='Nombre o Razón Social'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='pai_cliente',
            field=models.CharField(max_length=30, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='pob_cliente',
            field=models.CharField(max_length=30, verbose_name='Población'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='pro_cliente',
            field=models.CharField(max_length=30, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tipo_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.tipo_cliente', verbose_name='Tipo de Cliente'),
        ),
        migrations.AlterField(
            model_name='tipo_cliente',
            name='tipo_cliente',
            field=models.CharField(max_length=65, verbose_name='Tipo de Cliente'),
        ),
    ]
