# Generated by Django 4.1.3 on 2022-11-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_tipo_cliente_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ['id'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='tipo_cliente',
            options={'ordering': ['id'], 'verbose_name': 'Tipos de Cliente', 'verbose_name_plural': 'Tipos de Clientes'},
        ),
        migrations.AddField(
            model_name='clientes',
            name='email_cliente',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='fax_cliente',
            field=models.CharField(default='', max_length=20, verbose_name='Fax'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='mov1_cliente',
            field=models.CharField(default='', max_length=20, verbose_name='Móvil 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='mov2_cliente',
            field=models.CharField(default='', max_length=20, verbose_name='Móvil 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='pco_cliente',
            field=models.CharField(default='', max_length=65, verbose_name='Persona de Contacto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='tel1_cliente',
            field=models.CharField(default='', max_length=20, verbose_name='Teléfono 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='tel2_cliente',
            field=models.CharField(default='', max_length=20, verbose_name='Teléfono 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='url_cliente',
            field=models.URLField(default='', verbose_name='Web'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='wha_cliente',
            field=models.CharField(default='', max_length=20, verbose_name='Whatsapp'),
            preserve_default=False,
        ),
    ]
