# Generated by Django 4.1.3 on 2022-11-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_clientes_email_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cpo_cliente',
            field=models.CharField(max_length=10, null='True', verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='dir_cliente',
            field=models.CharField(max_length=65, null='True', verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email_cliente',
            field=models.EmailField(max_length=254, null='True', verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='fax_cliente',
            field=models.CharField(max_length=20, null='True', verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='mov1_cliente',
            field=models.CharField(max_length=20, null='True', verbose_name='Móvil 1'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='mov2_cliente',
            field=models.CharField(max_length=20, null='True', verbose_name='Móvil 2'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='pai_cliente',
            field=models.CharField(max_length=30, null='True', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='pco_cliente',
            field=models.CharField(max_length=65, null='True', verbose_name='Persona de Contacto'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='pob_cliente',
            field=models.CharField(max_length=30, null='True', verbose_name='Población'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='pro_cliente',
            field=models.CharField(max_length=30, null='True', verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tel1_cliente',
            field=models.CharField(max_length=20, null='True', verbose_name='Teléfono 1'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tel2_cliente',
            field=models.CharField(max_length=20, null='True', verbose_name='Teléfono 2'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='url_cliente',
            field=models.URLField(null='True', verbose_name='Web'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='wha_cliente',
            field=models.CharField(max_length=20, null='True', verbose_name='Whatsapp'),
        ),
    ]
